#window settings

WINDOW_WIDTH = 1650
WINDOW_HEIGHT = 1050
WINDOW_HEIGHT_HALF = WINDOW_HEIGHT // 2
WINDOW_WIDTH_HALF = WINDOW_WIDTH // 2
WORKING_SPACE_WIDTH = WINDOW_WIDTH * 7//8
WORKING_SPACE_HEIGHT = WINDOW_HEIGHT
WORKING_SPACE_WIDTH_HALF = WORKING_SPACE_WIDTH // 2
WORKING_SPACE_HEIGHT_HALF = WINDOW_HEIGHT // 2
ROTATE_SPEED = 0.03
FPS = 60

DEFAULT_ANGLE = 0
